# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num = 1
newNum = 1
total = 0

while newNum < 4000000
  newNum = num + newNum
	num = newNum - num
	total += newNum if newNum % 2 == 0

console.log total
